name: ckmr_snakemake
channels:
    - conda-forge
    - bioconda
    - pytorch
dependencies:
    - msprime
    - pyslim
    - tskit
    - numpy
    - scipy
    - pytorch
    - snakemake
    - jupyterlab
    - matplotlib
    - scikit-learn
    - slim
    - torchvision
    - gpustat
    - r-tidyverse
