import numpy as np
Ks = np.arange(5, 10, step = 0.25)
nreps = np.arange(100)

sim_pattern = "spatial_kin/spatial_sim_{K}_{rep}{ext}"
input_matrices = expand(sim_pattern, K=Ks, rep = nreps, ext=".csv")
pop_sizes = expand(sim_pattern, K=Ks, rep = nreps, ext=".N.csv")
rule all:
    input: 
        "labels.csv"
rule run_slim:
    output:
        "spatial_ts/spatial_sim_{K}_{rep}.trees"
    shell:
        "slim -d K={wildcards.K} -d 'OUTFILE=\"{output}\"' flat_maps.slim"
rule get_kin:
    input:
        "spatial_ts/spatial_sim_{K}_{rep}.trees"
    output:
        "spatial_kin/spatial_sim_{K}_{rep}.csv",
        temporary("spatial_kin/spatial_sim_{K}_{rep}.N.csv")
    shell:
        "python get_kin.py {input} {output} 30"
rule aggregate:
    input:
        input_matrices, pop_sizes 
    output:
        "labels.csv",
    shell:
        "cat {pop_sizes}  > labels.csv" 
